name: Backend Deployment

on:
  # 手動トリガーを有効化
  workflow_dispatch:
    inputs:
      branch:
        description: "Input the branch to deploy"
        required: true
        default: "main"
        type: string
      environment:
        description: "Select the environment to deploy"
        required: true
        type: choice
        options:
          - dev

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build, and Deploy Backend
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} # 選択したEnvironmentに基づいてシークレットを使用
    defaults:
      run:
        working-directory: ./backend

    steps:
      #1. リポジトリのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      #2. Python環境セットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      #3. AWS SAM CLIインストール
      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli
      
      #4. AWS認証
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ap-northeast-1

      - name: Check AWS CLI configuration (verify Identity)
        run: aws sts get-caller-identity

      #5. パラメータ設定
      - name: Set deployment variables
        id: vars
        shell: pwsh
        run: |
          $envName = "${{ inputs.environment }}"
          if ($envName -eq "development") {
            $configEnv = "dev"
            $stageName = "dev"
            $yourName  = "Development"
          } elseif ($envName -eq "staging") {
            $configEnv = "stg"
            $stageName = "stg"
            $yourName  = "Stage"
          } else {
            $configEnv = "prd"
            $stageName = "prd"
            $yourName  = "Production"
          }
          "CONFIG_ENV=$configEnv" | Out-File -FilePath $env:GITHUB_ENV -Append
          "STAGE_NAME=$stageName" | Out-File -FilePath $env:GITHUB_ENV -Append
          "YOUR_NAME=$yourName" | Out-File -FilePath $env:GITHUB_ENV -Append

      #6. ビルド
      - name: Run SAM build
        shell: pwsh
        run: ./build.ps1

      #7. AWS上へアップロード
      - name: Deploy SAM template
        shell: pwsh
        run: |
          sam deploy --stack-name "${{ secrets.AWS_LAMBDA_STACK_NAME }}" --s3-bucket "${{ secrets.AWS_S3_LAMBDA_BUCKET_NAME }}" --region ap-northeast-1 --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --config-env $env:CONFIG_ENV --parameter-overrides StageName=$env:STAGE_NAME YourName=$env:YOUR_NAME BucketName="${{ secrets.AWS_S3_DATA_BUCKET_NAME }}"
 
