name: Backend Deployment

on:
  # 手動トリガーを有効化
  workflow_dispatch:
    inputs:
      branch:
        description: "Input the branch to deploy"
        required: true
        default: "main"
        type: string
      environment:
        description: "Select the environment to deploy"
        required: true
        type: choice
        options:
          - dev

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build, and Deploy Backend
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} # 選択したEnvironmentに基づいてシークレットを使用
    defaults:
      run:
        working-directory: ./backend

    steps:
      #1. リポジトリのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      #2. Python環境セットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      #3. AWS SAM CLIインストール
      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli
      
      #4. AWS認証
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ap-northeast-1

      - name: Check AWS CLI configuration (verify Identity)
        run: aws sts get-caller-identity

      #5. 環境情報設定
      - name: Set Environment
        run: |
          ENV=${{ github.event.inputs.environment }}
          echo "CONFIG_ENV=$ENV" >> $GITHUB_ENV
          echo "TEMPLATE_FILE=template_${ENV}.yaml" >> $GITHUB_ENV

      #6. CI環境準備
      - name: Install dev dependencies
        run: pip install -r requirements-ci.txt

      #7. Lint（コード品質チェック）
      - name: Run Lint
        run: ruff check .

      #8. テスト実行
      - name: Run Tests
        run: pytest

      #9. ビルド
      - name: SAM build
        run: sam build -t $TEMPLATE_FILE

      #10. AWS上へアップロード
      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name ${{ secrets.AWS_LAMBDA_STACK_NAME }} \
            --s3-bucket ${{ secrets.AWS_S3_LAMBDA_BUCKET_NAME }} \
            --region ap-northeast-1 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --config-env $CONFIG_ENV \
            --parameter-overrides BucketName="${{ secrets.AWS_S3_DATA_BUCKET_NAME }}"
 